scylladb/scylla-ansible-roles

.gitignore
ansible-scylla-node/defaults/main.yml
ansible-scylla-node/tasks/RedHat.yml

After installing kernel-ml in CentOS, update grub and reboot

---

ansible-scylla-node/tasks/manager_agents.yml

MacOS safe pwgen command

---

ansible-scylla-node/tasks/common.yml

add cpuset

---

ansible-scylla-node/defaults/main.yml
ansible-scylla-node/templates/scylla.yaml.j2

make auth optional

---

ansible-scylla-monitoring/defaults/main.yml

update for monitoring to show timeouts and latencies

---

example-playbooks/rolling_ops/rolling_minorupgrade_restart.yml

fix rolling restart playbook task name

add example minorupgrade playbook

---

example-playbooks/run_cleanup/files/cleanup.sh
example-playbooks/run_cleanup/run_cleanup.yml

run also when scylla.yaml lacks data dir definition

rename repair to cleanup for cleanup playbook, make sure the script will

---

ansible-scylla-node/tasks/RedHat.yml

RPM option used instead and some cosmetic changes applied.

ELRepo related tasks improvements

---

.github/workflows/default.yml
ansible-scylla-manager/defaults/main.yml
ansible-scylla-monitoring/defaults/main.yml
ansible-scylla-monitoring/tasks/common.yml
ansible-scylla-node/defaults/main.yml
ansible-scylla-node/molecule/centos8/molecule.yml
ansible-scylla-node/molecule/ubuntu2004/molecule.yml
ansible-scylla-node/tasks/RedHat.yml
ansible-scylla-node/tasks/common.yml

Version update

---

example-playbooks/restore_scylla_manager_backup/restore.yaml

Major rework of the playbook which makes it actually work on multi-node clusters.
See more details in patches descriptions.

Restore from sm backup rework

---

ansible-scylla-manager/defaults/main.yml
ansible-scylla-manager/tasks/Debian.yml
ansible-scylla-manager/tasks/RedHat.yml
ansible-scylla-node/defaults/main.yml
ansible-scylla-node/tasks/Debian.yml
ansible-scylla-node/tasks/RedHat.yml

support for mixed base OS

---

ansible-scylla-node/tasks/common.yml

always generate monitoring config and agent

---

ansible-scylla-node/tasks/Debian.yml

Please merge if molecule will pass
( I tested this as part of https://github.com/scylladb/scylla-ansible-roles/pull/117 , this is just spinoff, since it's important to not get blocked by 117 )

Debian: don't upgrade all packages, just update cache

---

ansible-scylla-node/tasks/Debian.yml
ansible-scylla-node/templates/apt-pin-file.j2

Debian: get versioning of scylla package working with role

---

ansible-scylla-monitoring/tasks/Debian.yml

skip interactive query to allow adding repo

compatibility update for Ubuntu 22

---

ansible-scylla-manager/defaults/main.yml

Role ansible-scylla-manager: correct default variables

---

example-playbooks/run_cleanup/files/cleanup.sh

cleanup should skip non existent tables

---

ansible-scylla-node/tasks/manager_agents.yml

start_service set to false is not honored anymore

---

ansible-scylla-node/defaults/main.yml
ansible-scylla-node/tasks/common.yml
ansible-scylla-node/tasks/start_one_node.yml

Closes https://github.com/scylladb/scylla-ansible-roles/issues/149

ansible-scylla-node: Parametrize bootstrap wait time

---

ansible-scylla-node/defaults/main.yml
ansible-scylla-node/tasks/common.yml
ansible-scylla-node/templates/io_properties.yaml.j2

Closes https://github.com/scylladb/scylla-ansible-roles/issues/116

ansible-scylla-node: Make scylla_io_probe DC aware

---

ansible-scylla-monitoring/defaults/main.yml
ansible-scylla-monitoring/tasks/docker.yml

Closes https://github.com/scylladb/scylla-ansible-roles/issues/227
Closes https://github.com/scylladb/scylla-ansible-roles/issues/93

ansible-scylla-monitoring: Pass cql credentials to scylla-monitoring

---

ansible-scylla-node/defaults/main.yml
ansible-scylla-node/molecule/centos7/molecule.yml
ansible-scylla-node/molecule/centos8/molecule.yml
ansible-scylla-node/molecule/debian10/molecule.yml
ansible-scylla-node/molecule/debian9/molecule.yml
ansible-scylla-node/molecule/fedora/molecule.yml
ansible-scylla-node/molecule/ubuntu1604/molecule.yml
ansible-scylla-node/molecule/ubuntu1804/molecule.yml
ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
ansible-scylla-node/molecule/ubuntu2004/molecule.yml
ansible-scylla-node/tasks/common.yml
ansible-scylla-node/tasks/repair.yml

Closes https://github.com/scylladb/scylla-ansible-roles/issues/9

ansible-scylla-node: Verify if auth is enabled and adjust system_auth ks

---

ansible-scylla-node/defaults/main.yml
ansible-scylla-node/tasks/adjust_keyspace_replication.yml
ansible-scylla-node/tasks/common.yml

Closes https://github.com/scylladb/scylla-ansible-roles/issues/189

ansible-scylla-node: Verify if audit is enabled and adjust audit ks

---

ansible-scylla-node/handlers/main.yml
ansible-scylla-node/tasks/Debian.yml
ansible-scylla-node/tasks/RedHat.yml
ansible-scylla-node/tasks/common.yml
ansible-scylla-node/tasks/upgrade/post_upgrade.yml

This PR solves several issues related to 'node-exporter' and 'scylla-node-exporter' services.
Fixes: #249

Improves 'scylla-node-exporter' related code

---

ansible-scylla-node/handlers/main.yml
ansible-scylla-node/tasks/Debian.yml
ansible-scylla-node/tasks/RedHat.yml
ansible-scylla-node/tasks/common.yml
ansible-scylla-node/tasks/upgrade/post_upgrade.yml

Reverts scylladb/scylla-ansible-roles#250
CI is failing.

Revert "Improves 'scylla-node-exporter' related code"

---

ansible-scylla-node/tasks/common.yml

scylla: run scylla_bootparam_setup only when it exists

---

example-playbooks/rolling_ops/rolling_custom_build_install.yml

This playbook installs a custom Scylla build on a Debian system. See more explanations inside the file as inline comments.

rolling_ops: introduce rolling_custom_build_install.yml playbook

---

README.md

docs: Fix Readme

---

.github/workflows/ansible-scylla-monitoring.yml
.github/workflows/ansible-scylla-node.yml

Explicitly specify Python version we require.

scylla-node: be specific about Python version we need: 3.10

---

ansible-scylla-monitoring/defaults/main.yml

Fix the endless recursion in the corresponding default.

se scylla_cluster_name directlyscylla-monitoring: update scylla_cluster_name_for_alerts default to u
