- ansible-scylla-loader/tasks/RedHat.yml
- ansible-scylla-manager/tasks/RedHat.yml
- ansible-scylla-manager/tasks/add-clusters.yml
- ansible-scylla-monitoring/tasks/RedHat.yml
- ansible-scylla-node/tasks/RedHat.yml
Fixes #16 
Doubles the lock timeout to avoid failing build steps when yum doesn't release it's lock within 30 seconds.
> [#1927] Increased lock timeout for ech use of yum

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/Debian.yml
- ansible-scylla-node/tasks/ssl.yml
This PR fixes ansible-scylla-node to work on Debian hosts. Three things were fixed:
* correct `cert_path`
* Scylla installation
* removed not working perftune tasks
> Fix Debian installation

- ansible-scylla-manager/meta/main.yml
- ansible-scylla-node/meta/main.yml
Scylla server successfully starts on ubuntu focal after adding both this and the following PR:
https://github.com/scylladb/scylla-ansible-roles/pull/35
Not tested on production yet, nor have I attempted to install scylla manager.
> Support ubuntu 20.04 (focal)

- ansible-scylla-monitoring/tasks/Debian.yml
It works on both Debian and Ubuntu. Previously it worked only on Ubuntu.
> Use correct docker repository

- example-playbooks/async_extra/README.md
- example-playbooks/async_extra/action_plugins/async_task.py
- example-playbooks/async_extra/async_task_cmd.yml
- example-playbooks/async_extra/async_task_cmd_argv.yml
- example-playbooks/async_extra/async_task_script.yml
- example-playbooks/async_extra/async_task_script_fail.yml
- example-playbooks/async_extra/cmd.yml
- example-playbooks/async_extra/cmd_argv.yml
- example-playbooks/async_extra/install.sh
- example-playbooks/async_extra/script.yml
- example-playbooks/async_extra/sleep.sh
- example-playbooks/run_cleanup/files/cleanup.sh
- example-playbooks/run_cleanup/run.sh
- example-playbooks/run_cleanup/run_cleanup.yml
- script support
- cmd support
- failed jobs warning
- run cleanup async
magic:
```
- name: Run cleanup
async_task:
script:  files/cleanup.sh
alias: scylla_cleanup
async: 2592000
retries: 43200
delay: 60
register: cleanup_output
```
Run
===
$ ./run.sh localhost
or
$ ANSIBLE_ACTION_PLUGINS=../async_extra/action_plugins ansible-playbook ./run_cleanup.yml -vvvv -l localhost -M ../async_extra/library
Note
===
it is critical to rework `./files/cleanup.sh` to exit with a non-zero error code if it actually fails. currently, it is not. but that's outside of the pr series.
> Async script

- ansible-scylla-node/tasks/common.yml
> scylla node role: retry for check API access at least 90x

- ansible-scylla-node/tasks/common.yml
Resolve vars['ansible_'~scylla_nic].ipv4.address into a fact
in order to be able to use it in a loop.
> ansible-scylla-node: resolve another composite variable

- ansible-scylla-node/tasks/common.yml
When detecting if a node is a seed a 'broadcast_address' has
to be considered and not anything else.
> ansible-scylla-node: resolve scylla_broadcast_address and use it

- ansible-scylla-loader/tasks/Debian.yml
- ansible-scylla-monitoring/tasks/Debian.yml
For monitoring and loader roles
> Only update apt cache, don't upgrade all packages for Ubuntu

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
- extra-playbooks/get_scylla_version.yml
Scylla Role supports a 'latest' label as a Scylla Version (`scylla_version` parameter) however when we persist the Role state we should avoid storing `scylla_version: latest` in order to avoid unintentional SW upgrades next time we run a Role.
We should store the actual Scylla version instead.
This PR introduces a helper playbook that allows fetching a Scylla version and also "breaks" the default the way that would require to always explicitly provide a `scylla_version` parameter when a Role is executed.
> Add get scylla version playbook

- ansible-scylla-node/tasks/Debian.yml
- ansible-scylla-node/templates/apt-pin-file.j2
Reverts scylladb/scylla-ansible-roles#125
I think this PR breaks a regular upgrade flow when the installed version is not the latest:
```
$ apt list -a scylla-enterprise 2>/dev/null | grep 2021.1.9 
scylla-enterprise/stable 2021.1.11-0.20220516.8e6c9917c-1 amd64 [upgradable from: 2021.1.9-0.20220208.86e3ea4df-1]
scylla-enterprise/stable,now 2021.1.9-0.20220208.86e3ea4df-1 amd64 [installed,upgradable to: 2021.1.11-0.20220516.8e6c9917c-1]
```
> Revert "Debian: get versioning of scylla package working with role"

- ansible-scylla-node/README.md
- ansible-scylla-node/tasks/Debian.yml
- ansible-scylla-node/tasks/Debian_install.yml
- ansible-scylla-node/tasks/upgrade/pre_upgrade.yml
- ansible-scylla-node/tasks/upgrade/upgrade_debian.yml
- ansible-scylla-node/tasks/upgrade/upgrade_ubuntu.yml
- ansible-scylla-node/templates/apt-pin-file.j2
This patch fixes for the 'installation' and the 'upgrade' paths.
The corresponding code is moved into a separate tasks file:
Debian_install.yml; and used from both locations.
Fixes #102
> ansible-scylla-node: fix specific version installation on Debian

- ansible-scylla-monitoring/defaults/main.yml
- ansible-scylla-monitoring/tasks/docker.yml
Uses `scylla_monitoring_alertdata_path` variable, passed on to `start-all.sh`.
Deafults to "{{ scylla_monitoring_deploy_path }}/alertdata".
Fixes #124
> scylla-ansible-monitoring: persist alertmanager data by default.

- ansible-scylla-monitoring/tasks/common.yml
- ansible-scylla-monitoring/tasks/docker.yml
docker.yml used scylla_monitoring_data_path instead of
scylla_monitoring_data_path due to a typo.
Also, explicitly create the abovementioned directory.
> scylla-ansible-monitorin: fix directory used for alert data.

- ansible-scylla-node/defaults/main.yml
It makes no sense for `upgrade_major` to be set to `True`. Major upgrades must **always** be explicitly requested, whereas minor ones should always have the precedence.
> Node Role - upgrade_major should default to False

- ansible-scylla-node/tasks/ssl.yml
- ansible-scylla-node/templates/cqlshrc.j2
Our previous implementation of ssl.yml incorrectly generated a self-signed certificate mistakenly named as a "CA".
As it turns out, a CA certificate needs to have some specific characteristics in order to be considered a proper Certificate Authority.
Due to that, the CA certificate couldn't be used by clients to properly authenticate against the nodes, in such a way that clients were required to skip TLS verification in order to connect.
This mini-series corrects that situation and also updates the generated `cqlshrc` template to properly use the CA certificate created.
Fixes #161 
Closes #161
> Node role - Correctly generate CA certificate and update references

- example-playbooks/run_cleanup/run_cleanup.yml
This change allows the playbook to be run on multiple nodes at the same time
Ref: #169
Signed-off-by: Eduardo Benzecri <eduardo.benzecri@scylladb.com>
> example-playbooks: Implements batch size

- ansible-scylla-node/defaults/main.yml
- example-playbooks/replace_node/README.md
'enable_sstables_mc_format:true' is a default since Scylla Ent 2020.1.0. No need to specify it explicitly any more.
Fixes #85
> scylla_node: remove 'enable_sstables_mc_format: true'

- ansible-scylla-node/tasks/upgrade/node_verification.yml
When the upgrade feature was done, it was decided to not use the build number. If the full version is specified, the check will fail.
Fixes #308
Signed-off-by: Eduardo Benzecri <eduardo.benzecri@scylladb.com>
> ansible-scylla-node: Fixes version check after a minor upgrade is done

- ansible-scylla-node/README.md
- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/common.yml
- example-playbooks/add_cluster_nodes/add_cluster_nodes.yml
- example-playbooks/replace_node/replace_node.yml
- example-playbooks/scylla_deploy/nodes.yml
Closes https://github.com/scylladb/scylla-ansible-roles/issues/90
> ansible-scylla-node: Remove dependency on geerlingguy.swap and start using scylla_swap_setup instead

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/upgrade/main.yml
This patch will add the ability of skipping any version control when an upgrade should take place.
Fixes #210
Signed-off-by: Eduardo Benzecri <eduardo.benzecri@scylladb.com>
> ansible-scylla-node: Adds an option to force the upgrade

- ansible-scylla-node/tasks/upgrade/node_verification.yml
Instead of comparing if the versions are equal, the version installed should match partially or totally the detected one.
This path was done because of:
Scylla package version (obtained as an Ansible's fact): 2021.1.17-0.20221221.5318a7fec-1
Scylla version (scylla --version output): 2021.1.17-0.20221221.5318a7fec
Fixes: #212
Signed-off-by: Eduardo Benzecri <eduardo.benzecri@scylladb.com>
> ansible-scylla-node: Updates post-upgrade version check

- ansible-scylla-node/tasks/common.yml
We should never ignore errors in general and when setting the RAID up in particular.
If RAID exists, and it doesn't correspond to the configuration required - this requires an Operator intervention.
Fixes #152
> scylla_node: don't ignore errors when setting up a raid

- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
Since scylla_seeds parameters is hardocded, it's much more stable to have the whole network set up pinned as well.
> tests: pin ip addresses in molecule setup

- ansible-scylla-node/tasks/common.yml
Run scylla_raid_setup only if there isn't a scylla mount yet.
The previous logic tried to check the number of disk in md0 SW RAID. This was bogus for multiple reasons:
1) Scylla RAID can be *not* md0 but any mdX. By default scylla_raid_setup
is going to try an unused mdX for X'es between 0 and 9.
2) This logic breaks even worse for a single NVMe card configurations -
these won't even use SW RAID.
This patch changes the logic to explicitly check for mounts with 'scylla' in their mount point name. If exists - scylla_raid_setup won't be called.
This will avoid scylla_raid_setup from being called if that mount had been created using Scylla Role, because Role calls 'scylla_raid_setup' with a default mount point name, which will be '/var/lib/scylla'.
In any other case - scylla_raid_setup is …
> scylla-node: improve idempotence of RAID setup

- example-playbooks/run_decommission/run_decommission.yml
Improvements:
- async_tasks parameters are now variables
- Aborts the whole playbook execution is the decommission fails
- Adds the ability of disable and stop scylla-server service and poweroff the instance if required
> run_decommission.yml: Improves the decomissioning process

- example-playbooks/run_decommission/run_decommission.yml
This PR contains:
- A fix that will allow the playbook to remove the async lock directory granting the required permissions
- A fix will force and pass several async module variables as int
> run_decommission.yml: Batch of small fixes

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/ssl.yml
Today, if someone wants to use their own node certificates or sign the certificates with their own CA this is not possible, even though it's described on the documentation (https://github.com/scylladb/scylla-ansible-roles/wiki/ansible-scylla-node:-Deploying-a-Scylla-cluster#ssl-configuration-for-scylla-nodes) as possible.
This PR adds this functionality following the instructions already described in the documentation. 
Closes https://github.com/scylladb/scylla-ansible-roles/issues/11
> ansible-scylla-node: Allow user to provide their own certificates

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
- ansible-scylla-node/tasks/common.yml
Currently, by default, the role will always try to replace the io_properties.yaml file according to scylla_io_setup output or pre-defined io_properties variable. However, it makes more sense to avoid touching this file if it already exists, since the user might be, for example, performing some kind of test which requires io_properties to use different values for different nodes.
This patch changes the default behavior, and now io_properties.yaml will only be replaced if the flag `always_replace_io_properties`, also added on this patch, is set to True.
> ansible-scylla-node: Use already existing io_properties.yaml by default

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
- ansible-scylla-node/tasks/common.yml
Reverts scylladb/scylla-ansible-roles#236
> Revert "ansible-scylla-node: Use already existing io_properties.yaml by default"

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/common.yml
Currently, by default, the role will always try to replace the io_properties.yaml and io.conf files according to scylla_io_setup output or pre-defined io_properties and io_conf variables. However, it makes more sense to avoid touching these files if they already exist, since the user might be, for example, performing some kind of test which requires io_properties/io.conf to use different values for different nodes.
This patch changes the default behavior, and now these files will only be replaced if the flags `always_replace_io_properties` and `always_replace_io_conf', added on this patch, are set to True.
> ansible-scylla-node: Use already existing io_properties.yaml and io.conf by default

- example-playbooks/manage_users/README.md
- example-playbooks/manage_users/create_user.yml
- example-playbooks/manage_users/manage_users.yml
- example-playbooks/manage_users/vars/main.yml
This PR adds a playbook which allows the creation of cql users and deletes the default cassandra user as recommended in scylla's documentation -> {https://docs.scylladb.com/stable/operating-scylla/security/enable-authorization.html#enabling-authorization}.
By default this playbook will add the users scylla_admin (superuser), scylla_cql_monitor and customer_admin,
but you can change the list of users and permissions by overriding the variable users.
Every user defined in this playbook must be also defined in the inventory file under the section [cql_credentials] followed
by its password.
```
E.g.:
[cql_credentials]
scylla_admin=password1
scylla_cql_monitor=password2
customer_admin=password3
```
Operations allowed:
* Addition of users
* Addition of permissions for any user (Removing …
> Add default users

- example-playbooks/manage_users/manage_users.yml
Passing ignore errors to the task included works only with import_tasks. This patch replaces include_tasks with import_tasks in order for the ignore_errors to work. This ignore_errors is necessary because it's ok for the task of creating scylla_admin to fail if scylla_admin already exists.
> manage_user.yml: Use import_task instead of include_tasks for creating admin_user

- ansible-scylla-monitoring/defaults/main.yml
- ansible-scylla-monitoring/tasks/common.yml
Currently we're using the information from nodetool status to generate scylla_servers.yml.
However, it might be useful to use the information from the inventory, if we want, for example,
to use the dns names. This patch adds a variable `use_nodetool_status_with_genconfig` and sets it
to False as default. Whenever this variable is set to False, the role will generate scylla_servers.yml
based on the information from the inventory. Note that in order for this to work, the dc variable
must be defined for all the nodes in the inventory.
e.g.:
```
[scylla]
node1 dc=dc1
node2 dc=dc1
node3 dc=dc1
```
> ansible-scylla-monitoring: Allow gathering names/ips from the inventory to generate scylla_servers.yml

- ansible-scylla-node/handlers/main.yml
- ansible-scylla-node/tasks/common.yml
This patch enforces 'scylla-fstrim.timer' service to be enabled and started by default after 'scylla_fstrim_setup' is executed.
Ref: #246
> ansible-scylla-node: Starts 'scylla-fstrim.timer' service automatically

- example-playbooks/manage_users/vars/main.yml
Currently, the customer_admin user is not able to change the password for other users. This patch fixes this by giving ALTER permission on ALL roles to this user. This is not ideal, since now the customer_admin user will be able to change passwords even for superusers, but it's the only option we have until the following issues are fixed:
- https://github.com/scylladb/scylladb/issues/14277
- https://github.com/scylladb/scylladb/issues/14279
> manage_users.yml: Add ALTER permission on ALL ROLES to customer_admin

- ansible-scylla-monitoring/templates/rule_config.yml.j2
Since "prometheus.rules.yml: Use severity as string instead of numbers" Alert Manager is going to use string severities values, like "warn", "error", etc.
However the same patch introduced a regression by inverting the severities: https://github.com/scylladb/scylla-monitoring/issues/2029
While we are waiting for a fix let's "hack" it so that things continue working.
> scylla-monitoring: rule_config.yml.j2: add routes for string severities

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
- ansible-scylla-node/tasks/Debian.yml
- ansible-scylla-node/tasks/Debian_install.yml
- ansible-scylla-node/tasks/RedHat.yml
- ansible-scylla-node/tasks/main.yml
Scylla should only be upgraded via the corresponding 'upgrade' flow. Other than that the Role should only install binaries if they haven't been installed yet.
If they have already been installed but the version differs from the one specified via 'scylla_version' Role will error out by default.
The Operator may decide to skip the check above using 'skip_installed_scylla_version_check'.
> scylla-node: don't ever install scylla on top of already installed one

- example-playbooks/rolling_ops/rolling_major_upgrade.yml
- example-playbooks/rolling_ops/rolling_minor_upgrade.yml
Sets skip_installed_scylla_version_check to true, otherwise the playbook won't be able to run the required upgrade
> rolling_*_upgrade: Adds skip_installed_scylla_version_check

- ansible-scylla-node/tasks/Debian_install.yml
This variable must be called upgrade_version as it was specified in the corresponding commit.
> ansible-scylla-node: Replaces upgrade_scylla variable

- ansible-scylla-node/tasks/upgrade/main.yml
Adds 2023.1 version to the existing operating systems of the support matrix
> ansible-scylla-node: Adds 2023.1 to the version matrix

- ansible-scylla-node/tasks/upgrade/main.yml
This patch adds support for Ubuntu 22.04 based on https://opensource.docs.scylladb.com/stable/getting-started/os-support.html
> ansible-scylla-node: Adds Ubuntu 22.04 to the support matrix

- ansible-scylla-monitoring/templates/rule_config.yml.j2
"prometheus.rules.yml: re-map the number to level alerts" patch is present in Scylla Monitoring 4.4.5 and later.
We can revert the workaround now.
Reverts 9653157222dd30c879bb34aabd1011527d2b11d1
> rule_config.yml.j2: revert the severity workaround

- ansible-scylla-monitoring/templates/rule_config.yml.j2
"3" corresponds to "error"
"4" - to "critical"
So, we want to create an URGENT email for "error" and "critical" (not "warn").
> rule_config.yml.j2: fix a mistake in severity mapping

- ansible-scylla-monitoring/templates/rule_config.yml.j2
This reverts commit c84fb789df3d18d7478f23cb9214fc09481bc119.
> Revert "ansible-scylla-monitoring: Updates SMTP server used by default"

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/common.yml
- ansible-scylla-node/tasks/handle_encryption_at_rest_keys.yml
- ansible-scylla-node/templates/scylla.yaml.j2
This PR adds the following features to the role:
* The ability of managing table keys and system keys
* The ability of enabling/disabling system encryption 
Note that enabling **data encryption** is not part of this PR and needs to be done manually by the user.
The following tests were executed:
* Validate that if `handle_system_keys` is set to `true`, any keys inside `localhost_system_key_directory` will be copied to `system_key_directory`
* Validate that if `handle_table_keys` is set to `true`, any keys inside `localhost_table_key_directory` will be copied to `table_key_directory`
* Validate that if any already existing key in the `system_key_directory` has a different content from a key with the same name in the `localhost_system_key_diretory`, the role will fail.
* Validate that if …
> ansible-scylla-node: Add support for encryption at rest

- ansible-scylla-monitoring/templates/rule_config.yml.j2
Aggregate by an alert name and the severity (before that was only by severity) and then include both an alert name and its severity in the corresponding email subject.
As a result for tooManyFiles alert with a 'warn' severity a subject is going to look like this:
[PRODUCTION] tooManyFiles warn: URGENT Managed-Services - Cluster:cluster-name-goes-here
> rule_config.yml.j2: include the alert name and severity in the subject

- ansible-scylla-loader/tasks/Debian.yml
- ansible-scylla-node/tasks/Debian.yml
There is no need to call update-java-alternatives explicitly since openjdk-8-jre-headless .deb package invokes it as a post-install action.
Tested on Ubuntu 20.04 on both x86 and on arm64 HW.
Fixes #325
> Node/Loader Roles: Debian.yml: remove explicit update-java-alternatives call

- ansible-scylla-node/defaults/main.yml
This variable was removed by mistake in e42ec43
> ansible-scylla-node: Add default scylla_seeds back

- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
In the latest OSS version (5.4.0), if we use the defaults from Scylla we'll see the following error:
`init - Bad configuration: consistent_cluster_management requires schema commit log to be enabled`
This happens because consistent_cluster_management is set to true and force_schema_commit_log is set to false by default.
This PR fixes this error in our CI by setting force_schema_commit_log to true in scylla_yaml_params.
> molecule: Set force_schema_commit_log to true

- ansible-scylla-node/tasks/Debian.yml
Before this patch, if a key with a specific ID already installed was updated (because it was expired, for example), the key won't be locally updated causing and APT failure.
This patch ensures the usage of the latest apt key available.
> ansible-scylla-node: Enforces the installation of each APT key set

- ansible-scylla-node/tasks/Debian.yml
The task installing gnupg2 runs the equivalent to `apt update` before moving forward
due to `update_cache` being set to `true`. However if this role is being executed for
an old cluster which has an expired key, the `apt update` will fail.
In order to prevent that, this patch does the following:
* Removes keyring file only if gnupg2 is already installed
* Removes scylla repo keys only if gnupg2 is already installed
* Installs gnupg2 only if it's not installed before setting up the keys
> ansible-scylla-node: Update gpg keys before running apt update

- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- ansible-scylla-node/tasks/common.yml
Assuming `scylla_io_probe == true`, this `run_once` had the following logic:
* If `scylla_io_probe_dc_aware` was false, the block would run only once and copy the io_properties from the first node to all the others
* If it was true the block would run for all the hosts
However, having `scylla_io_probe_dc_aware` set to false means that we don't know if the nodes configuration will be the same, meaning that we'd rather measure io_properties per node than copy it from the first node.
This PR fixes this problem by removing the `run_once`.
Now, we'll only copy io_properties to other nodes in the following scenarios:
* if both, `scylla_io_probe` and `scylla_io_probe_dc_aware` are set to `true`, then we copy the io_properties from the first node of each DC to all the others of the same DC.
* if …
> ansible-scylla-node: Remove run_once from io_properties block and fix CI

- ansible-scylla-node/tasks/common.yml
- ansible-scylla-node/tasks/generate_tokens.yml
- ansible-scylla-node/tasks/start_one_node.yml
Hello,
I recently wanted to deploy a scylladb cluster with this playbook, I encountered a small problem when I redefined the scylla_rpc_address varriable to specific IP, the start_one_node task waits for scylla to be up on the wrong address (listen_address) and never succeeds.
> scylla-node: use rpc_address instead of listen_address on wait CQL port to be up

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
- ansible-scylla-node/tasks/common.yml
Add missing --no-cpuscaling-setup and --no-fstrim-setup (we explicitly setup these later in the play) and make sure to always call `scylla_setup` - with the parameters we call it it should be safe to call it even when scylla server is already running.
We also don't need to give '--nic {{ scylla_nic }} --setup-nic-and-disks' parameters because they are canceled by --no-sysconfig-setup at the end of the command line and because we are going to call scylla_sysconfig_setup later in the play explicitly.
Fixes #339
> scylla-node: fix scylla_setup call

- ansible-scylla-manager/tasks/add-clusters.yml
Allow updating existing clusters with a new metadata. Before this patch if the cluster is already added to SM via 'sctool cluster add' there was not way to update its configuration via Manager Role.
> scylla-manager: update existing cluster with provided metadata

- ansible-scylla-manager/README.md
- ansible-scylla-manager/defaults/main.yml
- ansible-scylla-node/README.md
- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/centos7/molecule.yml
- ansible-scylla-node/molecule/centos8/molecule.yml
- ansible-scylla-node/molecule/debian10/molecule.yml
- ansible-scylla-node/molecule/debian9/molecule.yml
- ansible-scylla-node/molecule/fedora/molecule.yml
- ansible-scylla-node/molecule/ubuntu1604/molecule.yml
- ansible-scylla-node/molecule/ubuntu1804/molecule.yml
- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- ansible-scylla-node/molecule/ubuntu2004/molecule.yml
- ansible-scylla-node/tasks/set_default_repo.yml
- ansible-scylla-node/tasks/upgrade/upgrade_debian.yml
- ansible-scylla-node/tasks/upgrade/upgrade_redhat.yml
- ansible-scylla-node/tasks/upgrade/upgrade_ubuntu.yml
- example-playbooks/scylla_deploy/manager.yml
- example-playbooks/scylla_deploy/nodes.yml
Starting March 5 http access to downloads.scylladb.com is going to be blocked. Let's switch to using https.
Ref scylladb/scylla-pkg#3764
> all-roles: use HTTPS for accessing downloads.scylladb.com

- ansible-scylla-node/tasks/generate_tokens.yml
'dc_suffix' has to be appended to the 'DC' variable when defined.
Fixes #349
> ansible-scylla-node: Add support for dc_suffix in generate_tokens task

- ansible-scylla-node/defaults/main.yml
The pipe needs to be added in order for the value to be read as a multi-line string.
Closes https://github.com/scylladb/scylla-ansible-roles/issues/374
> ansible-scylla-node: Fix io_properties example

- example-playbooks/replace_node/replace_node.yml
- example-playbooks/replace_node/vars/main.yml
When we're working in a cluster with mixed CPUSETs, it might be necessary to disable RBNO during a replace to avoid repair reader timeouts.
Having that in mind, this PR adds an option to disable RBNO only during the replace.
> replace_node.yml: Allow disabling RBNO for the new node during replace

- ansible-scylla-node/defaults/main.yml
Allowing using ports from 2000 up is dangerous because scylla uses ports 9xxx and 19xxx for listening on.
This may end up with scylla conflicting with itself if it OS uses one of these ports for "client" side of the socket (e.g. RPC sockets) and eventually failing with the following error:
(CQLServer error while listening on 172.29.160.241:9042 -> std::system_error (error system:98, posix_listen failed for address 172.29.160.241:9042: Address already in use))
Let's increase the lower bound to 20000.
> scylla-node: change net.ipv4.ip_local_port_range default tweaking

- ansible-scylla-node/defaults/main.yml
> ansible-scylla-node: update gpg keys for new Scylla versions

- example-playbooks/run_cleanup/files/cleanup.sh
instead of only getting first part until "-"
cql cannot have in table name "-" but
alternator can, so we cannot assume
that just first part until "-" is table name
logic has to be the other way, only whatever is after last "-" has to be deleted, all before is table name
fixes #387
> example_playbooks/run_cleanup: properly remove just hash of directory

- example-playbooks/replace_node/replace_node.yml
As explained in the documentation of the async module { https://github.com/scylladb/scylla-ansible-roles/tree/master/example-playbooks/async_extra#failures }, if an async job finishes with a bad result the task will not cleanup the job alias. So we need a separate task for doing that.
> replace_node.yml: Cleanup job aliases for 'nodetool drain' and 'stop scylla service' async tasks

- example-playbooks/replace_node/replace_node.yml
- example-playbooks/replace_node/vars/main.yml
From now on, let's block the replaced_node's broadcast address only if the 'block_replaced_node' var is set to True.
This way we'll be able to replace a node with itself when this variable is set to False.
> replace_node.yml: Add a block_replaced_node var

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/RedHat.yml
- ansible-scylla-node/tasks/common.yml
This patch adds a `detect_nvmes` field, which when set to True will use 'nvme list' command for getting the list of nvme devices in the machine and pass all of them to scylla_raid_setup.
> ansible-scylla-node: Allow auto-detecting nvme cards

- example-playbooks/replace_node/replace_node.yml
- example-playbooks/replace_node/vars/main.yml
Scylla has an `ignore_dead_nodes_for_replace` config which allows the user to ignore dead nodes during the replace and so far it was not supported by this playbook.
This PR adds support to this feature by adding a variable `dead_nodes_to_ignore`.
> replace_node.yml: Allow ignoring dead nodes during replace

- ansible-scylla-node/tasks/upgrade/node_verification.yml
This patch fixes the logic of how the version is checked during a minor upgrade, allowing to set a minor version as 'ABCD.E.F' instead of 'ABCD.E.F-G.H.I'
Fixes #401
> ansible-scylla-node: Fixes post-upgrade version check

- ansible-scylla-node/tasks/upgrade/main.yml
- ansible-scylla-node/tasks/upgrade/post_upgrade.yml
Versions sanity checks only make sense when one upgrades to official builds.
For custom builds upgrades one is going to disable these sanity checks anyway using upgrade_allow_user_manual_downgrade.
Therefore we can use MAJOR.MINOR.PATCH parts of installed and to-be-installed Scylla versions for sanity checking.
> ansible-scylla-node: prevent minor upgrade from failing when the destination scylla version is already installed

- ansible-scylla-node/defaults/main.yml
Have issue with fresh install, solves with new key added to keyring
```
TASK [ansible_scylla_node : Run "apt-get update"] *********************************************************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://downloads.scylladb.com/downloads/scylla/deb/debian-ubuntu/scylladb-6.2 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A43E06657BAC99E3, E:The repository …
```
> fix(repo_keys): add a43e06657bac99e3 key

- ansible-scylla-manager/meta/main.yml
- ansible-scylla-manager/tasks/main.yml
- ansible-scylla-node/tasks/common.yml
- ansible-scylla-node/tasks/generate_tokens.yml
- ansible-scylla-node/tasks/manager_agents.yml
- example-playbooks/async_extra/action_plugins/async_alias.py
- example-playbooks/async_extra/action_plugins/async_kill.py
- example-playbooks/async_extra/action_plugins/async_status_id.py
- example-playbooks/async_extra/action_plugins/async_task.py
- example-playbooks/async_extra/action_plugins/async_wait.py
- example-playbooks/async_extra/library/async_kill.py
- example-playbooks/async_extra/library/async_status_id.py
This patch introduces several fixes to allow compatibility with newer ansible versions.
Ansible versions 2.14 or older are EOL ([source](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix))
The patch introduces the following:
- Patches the async plugin library
- Patches scylla-ansible-manager to properly pass variables to the scylla-ansible-node role with newer Ansible versions.
- Patches a bug in deactivation of services: Services were listed as a fact but with a 'non-found' status.
- Detects errors when scylla-manager does not start.
Fixes #409: A newer Ansible version was required to execute properly with Ubuntu 24 which came with a newer Python version out-of-the-box, which was not supported by older Ansible versions.
> Compatibility with newer Ansible versions (tested 2.17.5)

- ansible-scylla-node/tasks/common.yml
NVMe disks should only be selected that are not in use, which should be the case when they are not mounted.
Fixes #407
> ansible-scylla-node: auto-detect NVMe: only use non-mounted disks.

- ansible-scylla-monitoring/tasks/docker.yml
The task names were prefixed with "grafana_docker.yml", whereas it should be prefixed with "docker.yml".
> ansible-scylla-monitoring: docker.yml: prefix task names correctly

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/common.yml
- ansible-scylla-node/templates/io_properties.yaml.j2
- ansible-scylla-node/templates/scylla-manager-agent.yaml.j2
This PR ensures that the JINJA templates output structured YAML values for scylla_manager_agent_config and io_properties instead of defaulting to JSON.
* Updates the io_properties comment to remove the pipe indicating a literal block style.
* Revises the scylla_manager_agent_config comment to clarify that the value is now expected as YAML.
> scylla-node/templates: properly handle structured values

- ansible-scylla-monitoring/defaults/main.yml
The default password was implicitly 'admin', but it is more prudent to be explicit about this case.
> ansible-scylla-monitoring: default grafana_admin_password

- ansible-scylla-manager/defaults/main.yml
- ansible-scylla-manager/meta/main.yml
- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/molecule/ubuntu2004-enterprise/molecule.yml
- example-playbooks/scylla_deploy/manager.yml
This PR introduces a number of improvements:
- The deprecated parameter `scylla_manager_repo_url` has been removed.
- The manager repo URLs have been updated to a more recent version.
- Manager role now can re-use certain defaults present in the scylla-node role which were being overridden
- The Manager its local ScyllaDB version can now be specified instead of always being the latest version.
- Certain outdated defaults in the Manager playbook have been removed.
> Manager improvements: Improved defaults and allow override of Manager its local ScyllaDB version

- example-playbooks/replace_node/README.md
- example-playbooks/replace_node/replace_node.yml
This pull request enhances the `replace_node.yml` playbook by introducing support for managing multiple Scylla Manager clusters. The changes ensure that tasks such as suspending, resuming, and repairing nodes are executed across all configured clusters, improving flexibility and scalability.
* **Task suspension and resumption**:
- Updated the suspension and resumption tasks to loop through all configured clusters (`scylla_clusters`) instead of targeting a single cluster (`scylla_cluster_name`). This allows managing multiple clusters simultaneously. (`[[1]](diffhunk://#diff-0669256df2a7ebd6796cee2327bcdfe0fe3fbcd3354f28bad82f7d09e1e69631L142-R144)`, `[[2]](diffhunk://#diff-0669256df2a7ebd6796cee2327bcdfe0fe3fbcd3354f28bad82f7d09e1e69631L354-R357)`)
* **Cluster identification and …
> Use the correct Scylla Cluster identity with Scylla Manager code parts

- ansible-scylla-node/defaults/main.yml
- ansible-scylla-node/tasks/main.yml
Explicitly verify that scylla_version is defined instead of relying on a "broken" default value.
This way, the error message is clear and the Role errors out early.
> main.yml: add a check to ensure scylla_version is defined

- ansible-scylla-monitoring/tasks/common.yml
- ansible-scylla-monitoring/tasks/run_nodetool_status.yml
Currently, since we are running `nodetool status` only on the first node, the task responsible for generating `scylla_servers.yml` will fail if the first node is down even if all the others are UP.
Having that in mind, let's run `nodetool status` on all nodes and then use the output of the first alive node for generating the file.
> ansible-scylla-monitoring: Try nodetool status on all nodes when use_nodetool_status_with_genconfig is used

- ansible-scylla-node/tasks/Debian_install.yml
This pull request updates the `ansible-scylla-node/tasks/Debian_install.yml` file to improve compatibility when filtering package versions during installation. The change ensures that architecture-independent packages (`all`) are included in addition to packages matching the system architecture.
Key change:
* Modified the `shell` command to filter package versions by both the system architecture (`dpkg --print-architecture`) and architecture-independent packages (`all`). This enhances compatibility by ensuring that relevant packages are not excluded during the filtering process.Let's finter not only by the current arch but also include platform independent packages.
> scylla-node: debian_install.yml: improve architecture filtering in version check
